Repository gap-packages/smallantimagmas, pull requests merged in 2024-08, with the labels that each got.

#41 feat: Add IsAntassociative test
  tst/test_antiassociative.tst
  tst/test_antimagma.tst
Labels: enhancement

#47 fix: Add documentation build
  .github/workflows/page-update.yaml
Labels: bug

#48 feat: Add serialisation
  data/all/1/.gitignore
  data/all/2/small_2.g.gz
  data/all/3/small_3.g.gz
  data/all/4/small_4.g.gz
  data/non-isomorphic/1/.gitignore
  data/non-isomorphic/2/small_2.g.gz
  data/non-isomorphic/3/small_3.g.gz
  data/non-isomorphic/4/small_4.g.gz
  lib/helper.gd
  lib/smallantimagmas.gi
  tst/test_helper_multiplication_table_converter.tst
Labels: enhancement

#49 fix: Fix gh-action name
  .github/workflows/page-update.yaml
Labels: bug

#51 fix: Change MagmaIsomorphism to operation
  lib/properties.gd
  lib/properties.gi
Labels: bug

#50 docs: Improve documentation
  PackageInfo.g
  README.md
  lib/properties.gd
  lib/smallantimagmas.gd
  lib/utils.gd
Labels: bug, enhancement

#52 feat: Add CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#54 feat: Add release drafter config
  .github/release-drafter.yaml
Labels: enhancement

#53 feat: Add release-drafter, pr-labeler
  .github/pr-labeler.yaml
  .github/workflows/pull-request-code-gap-docs.yaml
  .github/workflows/pull-request-code-gap-tests.yaml
  .github/workflows/pull-request-code-gaplint.yaml
  .github/workflows/pull-request-label.yaml
  .github/workflows/release-draft.yaml
  .github/workflows/release-page-update.yaml
Labels: feature

#55 release: Bump to v0.2.0
  PackageInfo.g
Labels: release

#56 feat: Test EnumeratorOfTuples keeps order
  tst/test_helper_multiplication_table_converter.tst
Labels: feature

#58 fix: Naming and docs copying
  .github/workflows/release-page-update.yaml
Labels: bug

#59 bump: Bump to v0.2.1
  PackageInfo.g
Labels: release

#60 bump: Bump to v0.2.2
  .github/workflows/release-page-update.yaml
  PackageInfo.g
Labels: bug, release

#61 bump: Bump to v0.2.3
  PackageInfo.g
Labels: bug, release

#62 feat: Add IsDeranged property
  lib/properties.gd
  lib/properties.gi
Labels: feature

#63 bump: Bump to v0.2.4
  PackageInfo.g
Labels: release

#64 feat: Add PackageInfo validation
  .github/workflows/pull-request-code-gap-docs.yaml
  .github/workflows/pull-request-code-gap-tests.yaml
  lib/properties.gd
  lib/properties.gi
  tst/test_0_metadata.tst
Labels: feature

#65 feat: Improve build process
  .github/workflows/release-page-update.yaml
Labels: feature

#66 bump: Bump to v0.2.5
  PackageInfo.g
Labels: release

#69 bump: Bump to v0.2.7
  .github/workflows/release-bump.yaml
  PackageInfo.g
Labels: release

#71 bump: Bump to v0.2.9
  PackageInfo.g
Labels: bug, release

#72 docs: Fix LICENSE
  LICENSE.txt
Labels: bug, documentation

#73 docs: Add release-badge
  README.md
Labels: feature

#75 docs: Fix typo
  lib/properties.gd
Labels: bug, documentation

#77 docs: Fix subtitle
  PackageInfo.g
  README.md
Labels: bug

#78 fix: Fix prefix for tar-ball
  .github/workflows/release-bump.yaml
Labels: bug

#79 bump: Bump to v0.2.10
  PackageInfo.g
Labels: release

#81 bump: Bump to v0.2.12
  PackageInfo.g
  tst/test_0_metadata.tst
Labels: release
